export const activityDe = {
    "people have successfully withdrawn": "Personen haben sich erfolgreich zurückgezogen",
	"Deadline": "Termin",
	"Congratulations! please apply for withdrawal asap": "Herzliche Glückwünsche! Bitte beantragen Sie die Auszahlung so schnell wie möglich",
	"more to complete": "mehr zu vervollständigen",
	"withdraw to": "sich zurückziehen",
	"Wheel of fortune": "Schicksalsrad",
	"Invite Friends": "Freunde einladen",
	"You can invite friends to win the lottery": "Sie können Freunde einladen, im Lotto zu gewinnen",
	"1 more time for each friend invited": "1 Mal mehr für jeden eingeladenen Freund",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "Das entnommene Bargeld wird auf dem Aktivitätskonto des Benutzers angesammelt, der gezogene Diamant wird in auf dem Aktivitätskonto angesammeltes Bargeld umgewandelt, das zur direkten Auszahlung gezogen werden kann und sofort abgehoben werden kann",
	"to your": "zu deinem",
	"Cash prizes drawn up to": "Verlosung von Geldpreisen",
	"during the activity can be withdrawn immediately": "während der Aktivität kann sofort zurückgezogen werden",
	"10% handling charge": "10 % Bearbeitungsgebühr",
	"will be charged for withdrawal": "werden für die Auszahlung belastet",
	"Each friend invited will be rewarded with": "Jeder eingeladene Freund wird mit belohnt",
	"100 coins +10% coin commission": "100 Münzen +10 % Münzprovision",
	"which will be distributed in the Yowin": "die im Yowin verteilt werden",
	"invite account": "Konto einladen",
	"and can be withdrawn separately": "und kann separat abgezogen werden",
	"Congratulations": "Herzliche Glückwünsche",
	"Win million Cash with all players Withdrawal arrives in seconds": "Gewinnen Sie Millionen Cash mit allen Spielern Die Auszahlung erfolgt in Sekunden",
	"Flop": "Flop",
	"Your friend invite you to join": "Ihr Freund lädt Sie zum Mitmachen ein",
	"For each friend invited,you will have an additional chance to draw": "Für jeden eingeladenen Freund haben Sie eine zusätzliche Chance zu ziehen",
	"To Invite": "Einladen",
	"Luck over 99% of users": "Glück über 99% der Benutzer",
	"DOWNLOAD APP": "LADE APP HERUNTER",
	"Get more cash&withdraw": "Holen Sie sich mehr Geld und heben Sie ab",
	"win more ruppes&withdraw": "Gewinnen Sie mehr Rupes und ziehen Sie sich zurück",
	"successfully withdrew": "erfolgreich zurückgezogen",
	"Easy Money": "Leichtes Geld",
	"Others": "Andere"
}