export const activityIt = {
    "people have successfully withdrawn": "persone si sono ritirate con successo",
	"Deadline": "Scadenza",
	"Congratulations! please apply for withdrawal asap": "Congratulazioni! si prega di richiedere il ritiro al più presto",
	"more to complete": "altro da completare",
	"withdraw to": "ritirarsi a",
	"Wheel of fortune": "Ruota della fortuna",
	"Invite Friends": "Invita gli amici",
	"You can invite friends to win the lottery": "Puoi invitare gli amici a vincere alla lotteria",
	"1 more time for each friend invited": "1 volta in più per ogni amico invitato",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "il denaro prelevato verrà accumulato sul conto attività dell'utente, il diamante estratto verrà convertito in denaro accumulato sul conto attività, prelevato al prelievo diretto può prelevare immediatamente",
	"to your": "alla tua",
	"Cash prizes drawn up to": "Premi in denaro estratti a",
	"during the activity can be withdrawn immediately": "durante l'attività può essere ritirato immediatamente",
	"10% handling charge": "10% di spese di gestione",
	"will be charged for withdrawal": "verrà addebitato per il ritiro",
	"Each friend invited will be rewarded with": "Ogni amico invitato sarà premiato con",
	"100 coins +10% coin commission": "100 monete + 10% di commissione monete",
	"which will be distributed in the Yowin": "che sarà distribuito nello Yowin",
	"invite account": "invitare l'account",
	"and can be withdrawn separately": "e può essere ritirato separatamente",
	"Congratulations": "Congratulazioni",
	"Win million Cash with all players Withdrawal arrives in seconds": "Vinci milioni di soldi con tutti i giocatori Il ritiro arriva in pochi secondi",
	"Flop": "Fallo",
	"Your friend invite you to join": "Il tuo amico ti invita a partecipare",
	"For each friend invited,you will have an additional chance to draw": "Per ogni amico invitato, avrai un'ulteriore possibilità di disegnare",
	"To Invite": "Invitare",
	"Luck over 99% of users": "Fortuna oltre il 99% degli utenti",
	"Luck over":'Fortuna oltre il',
	"of users":'degli utenti',
	"DOWNLOAD APP": "SCARICA APP",
	"Get more cash&withdraw": "Ottieni più contanti e prelievi",
	"win more ruppes&withdraw": "vincere più ruppes&ritirarsi",
	"successfully withdrew": "ritirato con successo",
	"Easy Money": "Soldi facili",
	"Others": "Altri",
	'Get':'Ottenere'
}