export const activityEs = {
	"Ambassador Recruitment": "Reclutamiento de embajadores",
	"Daily settlement commission": "Comisión de liquidación diaria",
	"For each invitation": "Por cada invitación",
	"We will AWARD an additional": "Premiaremos un adicional",
	"₹5": "₹ 5 ",
	"NO CAP": "SIN GORRA",
	"If you are a influencer and have your own promotion platform such as Youtube, Telegram, FB, Instagram, etc, or you have a wealth of fan resources": "Si eres un influencer y tienes tu propia plataforma de promoción como Youtube, Telegram, FB, Instagram, etc., o tienes una gran cantidad de recursos para fans.",
	"Please contact us, we can give you": "Por favor contáctenos, podemos darle ",
	"name": "nombre",
	"Phone NO": "Telefono no",
	"What social media do you use(Facebook/Ins/telegram/etc.)": "¿Qué redes sociales usas (Facebook / Ins / telegram / etc.) ",
	"Numbers of followers": "Número de seguidores",
	"Contant US(wa)": "Contant US (wa) ",
	"Copy": "Dupdo",
	"submit": "entregar",
	"As the beginning of the event, we only recruit": "Como inicio del evento, solo reclutamos ",
	"Ambassadors": "Embajadores",
	"besides": "además",
	"for every person invited": "por cada persona invitada ",
	"of the second-level reward share": "de la recompensa de segundo nivel ",
	"and": "y",
	"additional bonus of": "bonificación adicional de ",
	"person": "persona",
	"besides (Coin)100 for every person invited, 10% of the first-level reward share, and 5% of the second-level reward share": "además de (Moneda) 100 por cada persona invitada, el 10% de la recompensa de primer nivel y el 5% de la recompensa de segundo nivel ",
	"₹5 additional bonus of ₹5/person": "₹ 5 bono adicional de ₹ 5 / persona ",
	"Register now": "Regístrate ahora",
	"Submission succeed": "Sumisión exitosa ",
	"The audit duration is about 5 hours, please be patient and wait for the audit to pass": "La duración de la auditoría es de aproximadamente 5 horas, tenga paciencia y espere a que pase la auditoría ",
	"If you submit the information incorrectly, you can resubmit your registration": "Si envía la información de forma incorrecta, puede volver a enviar su registro ",
	"Congratulations": "Felicidades",
	"I know": "Sé",
	"From now on, if 100 users are invited within 7 days, in addition to the platforms existing rewards": "De ahora en adelante, si se invita a 100 usuarios dentro de los 7 días, además de las recompensas existentes de la plataforma",
	"100 gold coins /person plus 10% first-level reward plus 5% second-level reward": "100 monedas de oro / persona más 10% de recompensa de primer nivel más 5% de recompensa de segundo nivel ",
	"you will also receive": "también recibirás ",
	"additional promotional reward": "recompensa promocional adicional ",
	"₹5/person": "₹ 5 / persona ",
	"After reaching 100 valid invitees, you can contact the platforms staff to get the reward": "Después de llegar a 100 invitados válidos, puede ponerse en contacto con el personal de la plataforma para obtener la recompensa",
	"Note": "Nota",
	"Checkout Contact Whatsapp": "Pagar Contacto Whatsapp ",
	"If you need a dedicated promotional poster, you can contact our staff to design": "Si necesita un cartel promocional dedicado, puede ponerse en contacto con nuestro personal para diseñar ",
	"Social media addresses": "Direcciones de redes sociales",
	"Accumulated cash": "Efectivo acumulado ",
	"Withdraw": "Retirar",
	"Event period": "Período del evento ",
	"Withdrawl instruction": "Retirar instrucción ",
	"The cash can be withdrawn immediately after the event over. If the cash is not withdrawn in time, the system will automatically transfer the accumulated cash to your platform account, which can be withdrawn at any time~": "El dinero en efectivo se puede retirar inmediatamente después de que finalice el evento. Si el efectivo no se retira a tiempo, el sistema transferirá automáticamente el efectivo acumulado a su cuenta de plataforma, que puede retirarse en cualquier momento ~ ",
	"Invite Now": "Invitar ahora ",
	"Current Gift Pack": "Paquete de regalo actual ",
	"This cash gift pack can be opened by inviting": "Este paquete de regalo en efectivo se puede abrir invitando ",
	"people, and only": "personas, y solo ",
	"left you can get it": "a la izquierda puedes conseguirlo ",
	"Current Mystery Package": "Paquete misterioso actual ",
	"Congratulations! You get": "¡Felicidades! Usted obtiene",
	"The accumulated cash that has been distributed to you can be withdrawn immediately after the event ends": "El efectivo acumulado que se le ha distribuido puede retirarse inmediatamente después de que finalice el evento ",
	"The more friends you invite": "Cuantos más amigos invites",
	"the more gift boxes you get~": "cuantas más cajas de regalo recibas ~ ",
	"During the event period, invite users through this event page to get the opportunity to open the cash gift package.": "Durante el período del evento, invite a los usuarios a través de esta página del evento para tener la oportunidad de abrir el paquete de regalo en efectivo .",
	"The more friends you invite, the more gift packs you get": "Cuantos más amigos invites, más paquetes de regalo obtendrás ",
	"After the activity is over, you can withdraw cash. If you don`t withdraw cash in time, the system will automatically transfer the accumulated cash you get to your platform account": "Una vez finalizada la actividad, puede retirar efectivo. Si no retira efectivo a tiempo, el sistema transferirá automáticamente el efectivo acumulado que obtenga a la cuenta de su plataforma ",
	"Inviting friends can also get 100 gold coins/person on the platform, and corresponding 10% and 5% distribution rewards": "Invitar amigos también puede obtener 100 monedas de oro por persona en la plataforma, y ​​las correspondientes recompensas de distribución del 10% y el 5% ",
	"This event has ended": "Este evento ha terminado ",
	"This event has ended. If you have participated in the event, the reward has been issued to your account, please check.  Please stay tuned for the next event~": "Este evento ha terminado. Si ha participado en el evento, la recompensa se ha emitido a su cuenta, verifique. Estén atentos para el próximo evento ~ ",
	"You can still get platform rewards if you invite friends": "Aún puede obtener recompensas de plataforma si invita a amigos",
	"Rules": "Reglas",
	"Invitation": "Invitación",
	"record": "registro",
	"Invitation record": "Registro de invitación ",
	"Invite": "Invitación",
	"to join": "unir",
	"Activity Rules": "Reglas de actividad ",
	"You have One Cash bonus Please get it asap": "Tienes un bono en efectivo. Consíguelo lo antes posible ",
	"To complete": "Completar",
	"Start": "Comienzo",
	"Keep On! Do more task, Earn more money": "¡Continuar! Haga más tareas, gane más dinero ",
	"You got": "Tu tienes",
	"Note: On the first day, invitees up to 100  can contact our staff for withdrawal immediately": "Nota: El primer día, los invitados hasta 100 pueden comunicarse con nuestro personal para retirarse inmediatamente",
	"Get Gift": "Obtener regalo",
	"My Prize": "Mi premio",
	"100% WINNING": "100% GANADOR",
	"PLAY": "TOCAR",
	"It's a pity that you didn't win the prize, and you are presented with": "Es una lástima que no hayas ganado el premio y te presenten",
	"5 coins": "5 monedas",
	"The number of times today has been used up, please come tomorrow": "El número de veces que se ha agotado hoy, ven mañana.",
	"Congratulations": "Felicidades",
	"To balance": "Para equilibrar",
	"Congratulations on your gift card puzzles": "Felicitaciones por tus rompecabezas de tarjetas de regalo",
	"Congratulations to obtain": "Felicitaciones por obtener",
	"To Invite": "Invitar",
	"For every user invited to participate, you will get 1 chance to open the treasure box (cumulative)": "Por cada usuario invitado a participar, tendrá 1 oportunidad de abrir la caja del tesoro (acumulativa)",
	"Invite friends Let's open treasure box together": "Invitar amigos Abramos la caja del tesoro juntos",
	"When a complete card is generated, please click to exchange it directly. Please fill in the correct address and telephone information to prevent mailing failure": "Cuando se genera una tarjeta completa, haga clic para cambiarla directamente. Complete la dirección correcta y la información del teléfono para evitar fallas en el envío.",
	"Gift exchange": "Intercambio de regalos",
	"By opening the treasure box, you can get random puzzles, gather together four complete puzzles, which can be combined with mobile phones, cash, electronic products, gold coins and other gift cards": "Al abrir la caja del tesoro, puede obtener rompecabezas aleatorios, reunir cuatro rompecabezas completos, que se pueden combinar con teléfonos móviles, efectivo, productos electrónicos, monedas de oro y otras tarjetas de regalo.",
	"Gather together the puzzles": "Reúna los rompecabezas",
	"Every time you invite a new friend, you get a +1 chance to open your chest": "Cada vez que invitas a un nuevo amigo, tienes una oportunidad de +1 para abrir tu cofre",
	"only available on the same day": "solo disponible el mismo día",
	"1 chance to open a treasure box after login every day": "1 oportunidad de abrir una caja del tesoro después de iniciar sesión todos los días",
	"Each person will be given two chances to open the box, and each time you open the box, you will get 3 puzzles.": "Cada persona tendrá dos oportunidades para abrir la caja, y cada vez que abra la caja, obtendrá 3 rompecabezas.",
	"Open treasure box rule": "Regla de caja del tesoro abierta",
	"Deadline": "Plazo",
	"chances to treasure box": "posibilidades de caja del tesoro",
	"You have": "Tienes",
	"click here for more": "haga clic aquí para más",
	"Open treasure box": "Caja del tesoro abierta",
	"Download APP": "Descargar aplicación",
	"Collect gift cards": "Recoge tarjetas de regalo",
	"Money": "Dinero",
	"Address": "Habla a",
	"Name": "Nombre",
	"Enter address": "Ingresa la direccion",
	"Enter phone": "Ingrese el teléfono",
	"Enter name": "Ingrese su nombre",
	"My cards": "Mis cartas",
	"My puzzles": "Mis rompecabezas",
	"people have successfully withdrawn": "personas se han retirado con éxito",
	"Deadline": "Plazo",
	"Congratulations! please apply for withdrawal asap": "¡Felicidades! por favor solicite el retiro lo antes posible",
	"more to complete": "más para completar",
	"withdraw to": "retraerse a",
	"Wheel of fortune": "Rueda de la fortuna",
	"Invite Friends": "Invitar a amigos",
	"You can invite friends to win the lottery": "Puedes invitar a amigos a ganar la lotería.",
	"1 more time for each friend invited": "1 vez más por cada amigo invitado",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "el efectivo extraído se acumulará en la cuenta de actividad del usuario, el diamante extraído se convertirá en efectivo acumulado en la cuenta de actividad, extraído para retiro directo puede retirar inmediatamente",
	"to your": "para usted",
	"Cash prizes drawn up to": "Premios en metálico girados a",
	"during the activity can be withdrawn immediately": "durante la actividad se puede retirar inmediatamente",
	"10% handling charge": "10% cargo por manejo",
	"will be charged for withdrawal": "se cobrará por retiro",
	"Each friend invited will be rewarded with": "Cada amigo invitado será recompensado con",
	"100 coins +10% coin commission": "100 monedas +10% comisión de monedas",
	"which will be distributed in the Yowin": "que se distribuirá en el Yowin",
	"invite account": "invitar cuenta",
	"and can be withdrawn separately": "y se puede retirar por separado",
	"Congratulations": "Felicidades",
	"Win million Cash with all players Withdrawal arrives in seconds": "Gana millones en efectivo con todos los jugadores El retiro llega en segundos",
	"Flop": "Fracaso",
	"Your friend invite you to join": "Tu amigo te invita a unirte",
	"For each friend invited,you will have an additional chance to draw": "Por cada amigo invitado, tendrás una oportunidad adicional de dibujar",
	"To Invite": "Invitar",
	"Luck over 99% of users": "Suerte sobre el 99% de los usuarios",
	"Luck over":'Suerte sobre el',
	"of users":'de los usuarios',
	"DOWNLOAD APP": "DESCARGAR APLICACIÓN",
	"Get more cash&withdraw": "Obtén más efectivo y retira",
	"win more ruppes&withdraw": "gana más rupias y retira",
	"successfully withdrew": "se retiró con éxito",
	"Easy Money": "Dinero fácil",
	"Others": "Otros"
}