export const shopEs = {
	"Balance": "Equilibrio",
	"Cash & Prize": "Premio en efectivo",
	"Free Get": "Obtener gratis ",
	"Phone Numer": "Número de teléfono ",
	"First Name": "Primer nombre",
	"Last Name": "Apellido",
	"Address": "Habla a",
	"Please fill in the mailing address": "Por favor complete la dirección postal ",
	"Please enter the information completely": "Por favor ingrese la información completamente ",
	"Submitted successfully": "Enviado satisfactoriamente",
	"We will ship to you after review, please wait patiently": "Le enviaremos después de la revisión, espere pacientemente ",
	"Earn More Money": "Ganar más dinero",
	"Lucky Spin": "Lucky Spin ",
	"My rewards": "Mi recompensa",
	"Recharge card": "Recargar tarjeta",
	"Toy": "Juguete",
	"fragments": "fragmentos ",
	"Gift card": "Tarjeta de regalo",
	"View": "Vista",
	"": ""
}