export const activityVi = {
    "people have successfully withdrawn": "người đã rút tiền thành công",
	"Deadline": "Đường giới hạn",
	"Congratulations! please apply for withdrawal asap": "Xin chúc mừng! vui lòng đăng ký rút tiền càng sớm càng tốt",
	"more to complete": "nhiều hơn để hoàn thành",
	"withdraw to": "rút về",
	"Wheel of fortune": "Vòng quay may mắn",
	"Invite Friends": "Mời bạn bè",
	"You can invite friends to win the lottery": "Bạn có thể mời bạn bè để trúng xổ số",
	"1 more time for each friend invited": "1 lần nữa cho mỗi người bạn được mời",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "tiền mặt rút ra sẽ được tích lũy vào tài khoản hoạt động của người dùng, kim cương rút ra sẽ được chuyển thành tiền mặt tích lũy vào tài khoản hoạt động, rút ra rút tiền trực tiếp có thể rút ngay lập tức",
	"to your": "cho bạn",
	"Cash prizes drawn up to": "Giải thưởng tiền mặt lên đến",
	"during the activity can be withdrawn immediately": "trong quá trình hoạt động có thể được rút tiền ngay lập tức",
	"10% handling charge": "10% phí xử lý",
	"will be charged for withdrawal": "sẽ bị tính phí khi rút tiền",
	"Each friend invited will be rewarded with": "Mỗi người bạn được mời sẽ được thưởng",
	"100 coins +10% coin commission": "100 xu + 10% hoa hồng",
	"which will be distributed in the Yowin": "sẽ được phân phối trong Yowin",
	"invite account": "mời tài khoản",
	"and can be withdrawn separately": "và có thể được rút riêng",
	"Congratulations": "Xin chúc mừng",
	"Win million Cash with all players Withdrawal arrives in seconds": "Kiếm hàng triệu tiền mặt với tất cả người chơi Rút tiền sẽ đến sau vài giây",
	"Flop": "Rơi phịch xuống",
	"Your friend invite you to join": "Bạn của bạn mời bạn tham gia",
	"For each friend invited,you will have an additional chance to draw": "Đối với mỗi người bạn được mời, bạn sẽ có thêm cơ hội rút thăm",
	"To Invite": "Mời",
	"Luck over 99% of users": "May mắn hơn 99% người dùng",
	"DOWNLOAD APP": "TẢI ỨNG DỤNG",
	"Get more cash&withdraw": "Nhận nhiều tiền mặt và rút tiền",
	"win more ruppes&withdraw": "giành được nhiều ruppes hơn và rút tiền",
	"successfully withdrew": "rút tiền thành công",
	"Easy Money": "Kiếm tiền dễ dàng",
	"Others": "Khác"
}