export const activityId = {
	"Ambassador Recruitment": "Rekrutmen Duta",
	"Daily settlement commission": "Komisi penyelesaian harian",
	"For each invitation": "Untuk setiap undangan",
	"We will AWARD an additional": "Kami akan MENGHARGAI tambahan",
	"₹5": "5",
	"NO CAP": "TANPA CAP",
	"If you are a influencer and have your own promotion platform such as Youtube, Telegram, FB, Instagram, etc, or you have a wealth of fan resources": "Jika Anda seorang influencer dan memiliki platform promosi sendiri seperti Youtube, Telegram, FB, Instagram, dll, atau Anda memiliki banyak sumber daya penggemar",
	"Please contact us, we can give you": "Silahkan hubungi kami, kami dapat memberikan",
	"name": "nama",
	"Phone NO": "No Telepon",
	"What social media do you use(Facebook/Ins/telegram/etc.)": "Media sosial apa yang Anda gunakan (Facebook/Ins/telegram/dll.)",
	"Numbers of followers": "Jumlah pengikut",
	"Contant US(wa)": "Kontan AS(wa)",
	"Copy": "Salinan",
	"submit": "Kirimkan",
	"As the beginning of the event, we only recruit": "Sebagai awal acara, kami hanya merekrut",
	"Ambassadors": "duta besar",
	"besides": "di samping itu",
	"for every person invited": "untuk setiap orang yang diundang",
	"of the second-level reward share": "dari bagian hadiah tingkat kedua",
	"and": "dan",
	"additional bonus of": "bonus tambahan dari",
	"person": "orang",
	"besides (Coin)100 for every person invited, 10% of the first-level reward share, and 5% of the second-level reward share": "selain (Koin)100 untuk setiap orang yang diundang, 10% dari pembagian hadiah tingkat pertama, dan 5% dari pembagian hadiah tingkat kedua",
	"₹5 additional bonus of ₹5/person": "5 bonus tambahan 5/orang",
	"Register now": "Daftar sekarang",
	"Submission succeed": "Pengiriman berhasil",
	"The audit duration is about 5 hours, please be patient and wait for the audit to pass": "Durasi audit sekitar 5 jam, harap bersabar dan tunggu audit selesai",
	"If you submit the information incorrectly, you can resubmit your registration": "Jika Anda salah mengirimkan informasi, Anda dapat mengirimkan ulang pendaftaran Anda",
	"Congratulations": "Selamat",
	"I know": "Aku tahu",
	"From now on, if 100 users are invited within 7 days, in addition to the platforms existing rewards": "Mulai sekarang, jika 100 pengguna diundang dalam 7 hari, selain hadiah platform yang ada",
	"100 gold coins /person plus 10% first-level reward plus 5% second-level reward": "100 koin emas / orang ditambah 10% hadiah tingkat pertama ditambah 5% hadiah tingkat kedua",
	"you will also receive": "kamu juga akan menerima",
	"additional promotional reward": "hadiah promosi tambahan",
	"₹5/person": "5/orang",
	"After reaching 100 valid invitees, you can contact the platforms staff to get the reward": "Setelah mencapai 100 undangan yang valid, Anda dapat menghubungi staf platform untuk mendapatkan hadiah",
	"Note": "Catatan",
	"Checkout Contact Whatsapp": "Checkout Hubungi Whatsapp",
	"If you need a dedicated promotional poster, you can contact our staff to design": "Jika Anda membutuhkan poster promosi khusus, Anda dapat menghubungi staf kami untuk mendesain",
	"Social media addresses": "Alamat media sosial",
	"Accumulated cash": "Akumulasi uang tunai",
	"Withdraw": "Menarik",
	"Event period": "periode acara",
	"Withdrawl instruction": "Instruksi penarikan",
	"The cash can be withdrawn immediately after the event over. If the cash is not withdrawn in time, the system will automatically transfer the accumulated cash to your platform account, which can be withdrawn at any time~": "Uang tunai dapat ditarik segera setelah acara selesai. Jika uang tunai tidak ditarik tepat waktu, sistem akan secara otomatis mentransfer akumulasi uang tunai ke akun platform Anda, yang dapat ditarik kapan saja~",
	"Invite Now": "Undang Sekarang",
	"Current Gift Pack": "Paket Hadiah Saat Ini",
	"This cash gift pack can be opened by inviting": "Paket hadiah uang tunai ini dapat dibuka dengan mengundang",
	"people, and only": "orang, dan hanya",
	"left you can get it": "kiri Anda bisa mendapatkannya",
	"Current Mystery Package": "Paket Misteri Saat Ini",
	"Congratulations! You get": "Selamat! Anda mendapatkan",
	"The accumulated cash that has been distributed to you can be withdrawn immediately after the event ends": "Akumulasi uang tunai yang telah dibagikan kepada Anda dapat ditarik segera setelah acara berakhir",
	"The more friends you invite": "Semakin banyak teman yang Anda undang",
	"the more gift boxes you get~": "semakin banyak kotak hadiah yang kamu dapatkan~",
	"During the event period, invite users through this event page to get the opportunity to open the cash gift package.": "Selama periode acara, undang pengguna melalui halaman acara ini untuk mendapatkan kesempatan membuka paket hadiah uang tunai.",
	"The more friends you invite, the more gift packs you get": "Semakin banyak teman yang Anda undang, semakin banyak paket hadiah yang Anda dapatkan",
	"After the activity is over, you can withdraw cash. If you don`t withdraw cash in time, the system will automatically transfer the accumulated cash you get to your platform account": "Setelah aktivitas selesai, Anda dapat menarik uang tunai. Jika Anda tidak menarik uang tunai tepat waktu, sistem akan secara otomatis mentransfer akumulasi uang tunai yang Anda dapatkan ke akun platform Anda",
	"Inviting friends can also get 100 gold coins/person on the platform, and corresponding 10% and 5% distribution rewards": "Mengundang teman juga bisa mendapatkan 100 koin emas/orang di platform, dan hadiah distribusi 10% dan 5% yang sesuai",
	"This event has ended": "Acara ini telah berakhir",
	"This event has ended. If you have participated in the event, the reward has been issued to your account, please check.  Please stay tuned for the next event~": "Acara ini telah berakhir. Jika Anda telah berpartisipasi dalam acara tersebut, hadiah telah diberikan ke akun Anda, silakan periksa. Nantikan event selanjutnya~",
	"You can still get platform rewards if you invite friends": "Anda masih bisa mendapatkan hadiah platform jika Anda mengundang teman",
	"Rules": "Aturan",
	"Invitation": "Undangan",
	"record": "catatan",
	"Invitation record": "Catatan undangan",
	"Invite": "Undang",
	"to join": "bergabung",
	"Activity Rules": "Aturan Aktivitas",
	"You have One Cash bonus Please get it asap": "Anda memiliki satu bonus Uang Tunai, dapatkan secepatnya",
	"To complete": "Untuk menyelesaikan",
	"Start": "Awal",
	"Keep On! Do more task, Earn more money": "Terus! Lakukan lebih banyak tugas, Hasilkan lebih banyak uang",
	"You got": "kamu punya",
	"Note: On the first day, invitees up to 100  can contact our staff for withdrawal immediately": "Catatan: Pada hari pertama, undangan hingga 100 dapat menghubungi staf kami untuk penarikan segera",
	"Get Gift": "Dapatkan Hadiah",
	"My Prize": "Hadiahku",
	"100% WINNING": "100% MENANG",
	"PLAY": "BERMAIN",
	"It's a pity that you didn't win the prize, and you are presented with": "Sangat disayangkan bahwa Anda tidak memenangkan hadiah, dan Anda diberikan",
	"5 coins": "5 koin",
	"The number of times today has been used up, please come tomorrow": "Berapa kali hari ini telah habis, silakan datang besok",
	"Congratulations": "Selamat",
	"To balance": "Untuk menyeimbangkan",
	"Congratulations on your gift card puzzles": "Selamat atas teka-teki kartu hadiah Anda",
	"Congratulations to obtain": "Selamat mendapatkan",
	"To Invite": "Untuk mengundang",
	"For every user invited to participate, you will get 1 chance to open the treasure box (cumulative)": "Untuk setiap pengguna yang diundang untuk berpartisipasi, Anda akan mendapatkan 1 kesempatan untuk membuka kotak harta karun (kumulatif)",
	"Invite friends Let's open treasure box together": "Undang teman Mari kita buka kotak harta karun bersama",
	"When a complete card is generated, please click to exchange it directly. Please fill in the correct address and telephone information to prevent mailing failure": "Ketika kartu lengkap dibuat, silakan klik untuk menukarnya secara langsung. Harap isi alamat dan informasi telepon yang benar untuk mencegah kegagalan pengiriman",
	"Gift exchange": "Pertukaran hadiah",
	"By opening the treasure box, you can get random puzzles, gather together four complete puzzles, which can be combined with mobile phones, cash, electronic products, gold coins and other gift cards": "Dengan membuka kotak harta karun, Anda bisa mendapatkan teka-teki acak, mengumpulkan empat teka-teki lengkap, yang dapat digabungkan dengan ponsel, uang tunai, produk elektronik, koin emas, dan kartu hadiah lainnya.",
	"Gather together the puzzles": "Kumpulkan teka-teki",
	"Every time you invite a new friend, you get a +1 chance to open your chest": "Setiap kali Anda mengundang teman baru, Anda mendapat kesempatan +1 untuk membuka peti Anda",
	"only available on the same day": "hanya tersedia di hari yang sama",
	"1 chance to open a treasure box after login every day": "1 kesempatan untuk membuka kotak harta karun setelah login setiap hari",
	"Each person will be given two chances to open the box, and each time you open the box, you will get 3 puzzles.": "Setiap orang akan diberikan dua kesempatan untuk membuka kotak tersebut, dan setiap kali Anda membuka kotak tersebut, Anda akan mendapatkan 3 teka-teki.",
	"Open treasure box rule": "Buka aturan kotak harta karun",
	"Deadline": "Tenggat waktu",
	"chances to treasure box": "kesempatan untuk mendapatkan kotak harta karun",
	"You have": "Kamu punya",
	"click here for more": "klik di sini untuk lebih",
	"Open treasure box": "Buka kotak harta karun",
	"Download APP": "Unduh APLIKASI",
	"Collect gift cards": "Kumpulkan kartu hadiah",
	"Money": "Uang",
	"Address": "Alamat",
	"Name": "Nama",
	"Enter address": "Masukkan alamat",
	"Enter phone": "Masukkan telepon",
	"Enter name": "Masukkan nama",
	"My cards": "kartu saya",
	"My puzzles": "Teka-teki saya",
	"people have successfully withdrawn": "orang telah berhasil ditarik",
	"Deadline": "Tenggat waktu",
	"Congratulations! please apply for withdrawal asap": "Selamat! silahkan ajukan penarikan secepatnya",
	"more to complete": "lebih banyak untuk menyelesaikan",
	"withdraw to": "mundur ke",
	"Wheel of fortune": "Roda keberuntungan",
	"Invite Friends": "Mengundang teman-teman",
	"You can invite friends to win the lottery": "Anda dapat mengundang teman untuk memenangkan lotre",
	"1 more time for each friend invited": "1 kali lagi untuk setiap teman yang diundang",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "penarikan tunai akan diakumulasikan ke akun aktivitas pengguna, berlian yang ditarik akan diubah menjadi uang tunai yang diakumulasikan ke akun aktivitas, ditarik ke penarikan langsung dapat segera ditarik",
	"to your": "untuk Anda",
	"Cash prizes drawn up to": "Hadiah uang tunai diundi untuk",
	"during the activity can be withdrawn immediately": "selama aktivitas dapat segera ditarik",
	"10% handling charge": "10% biaya penanganan",
	"will be charged for withdrawal": "akan dikenakan biaya untuk penarikan",
	"Each friend invited will be rewarded with": "Setiap teman yang diundang akan diberi hadiah",
	"100 coins +10% coin commission": "100 koin + 10% komisi koin",
	"which will be distributed in the Yowin": "yang akan didistribusikan di Yowin",
	"invite account": "undang akun",
	"and can be withdrawn separately": "dan dapat ditarik secara terpisah",
	"Congratulations": "Selamat",
	"Win million Cash with all players Withdrawal arrives in seconds": "Menangkan jutaan Uang Tunai dengan semua pemain Penarikan tiba dalam hitungan detik",
	"Flop": "Kegagalan",
	"Your friend invite you to join": "Teman Anda mengundang Anda untuk bergabung",
	"For each friend invited,you will have an additional chance to draw": "Untuk setiap teman yang diundang, Anda akan memiliki kesempatan tambahan untuk menggambar",
	"To Invite": "Untuk mengundang",
	"Luck over 99% of users": "Keberuntungan lebih dari 99% pengguna",
	"Luck over":'Keberuntungan lebih dari',
	"of users":'pengguna',
	"DOWNLOAD APP": "UNDUH APLIKASI",
	"Get more cash&withdraw": "Dapatkan lebih banyak uang tunai & tarik",
	"win more ruppes&withdraw": "menangkan lebih banyak ruppe & tarik",
	"successfully withdrew": "berhasil mengundurkan diri",
	"Easy Money": "Uang mudah",
	"Others": "Yang lain",
	'Get':'Mendapatkan'
}