export const shopId = {
	"Balance": "Keseimbangan",
	"Cash & Prize": "Hadiah uang",
	"Free Get": "Dapatkan Gratis",
	"Phone Numer": "Nomor Telepon",
	"First Name": "Nama depan",
	"Last Name": "Nama keluarga",
	"Address": "Alamat",
	"Please fill in the mailing address": "Silahkan isi alamat surat",
	"Please enter the information completely": "Silakan masukkan informasi dengan lengkap",
	"Submitted successfully": "Berhasil dikirim",
	"We will ship to you after review, please wait patiently": "Kami akan mengirimkan kepada Anda setelah ditinjau, harap tunggu dengan sabar",
	"Earn More Money": "Hasilkan Lebih Banyak Uang",
	"Lucky Spin": "Putaran Keberuntungan",
	"My rewards": "Imbalan saya",
	"Recharge card": "isi ulang kartu",
	"Toy": "Mainan",
	"fragments": "pecahan",
	"Gift card": "Kartu ucapan",
	"View": "Melihat",
}