export const activityPt = {
    title: 'Ambassador Recruitment',
    subTitle: 'Daily settlement commission',
    invitation: 'Para cada convite,',
    AWARD: 'premiaremos um adicional de ',
    '₹5': 'R$0.5',
    'NO CAP': 'NO CAP',
    describe:
        'Se você é um influenciador e tem sua própria plataforma de promoção, como Youtube, Telegram, FB, Instagram, etc, ou tem muitos recursos de  fãs',
    'Please contact us, we can give you': 'Entre em contato conosco, podemos fornecer',
    name: 'Nome',
    'Phone NO': 'Telefone: Nº',
    'What social media do you use(Facebook/Ins/telegram/etc.)': 'Quais mídias sociais você usa',
    'Numbers of followers': 'Número de seguidores',
    'Contant US(wa)': 'Contato (Whatsapp)',
    Copy: 'Copy',
    submit: 'enviar',
    'As the beginning of the event, we only recruit': 'No início do evento, recrutamos apenas',
    Ambassadors: 'Embaixadores',
    besides: 'além de (moeda)',
    'for every person invited': 'para cada pessoa convidada',
    'of the second-level reward share': 'da parcela de recompensa para o primeiro nível e',
    and: 'da',
    'additional bonus of': 'Bônus adicional',
    person: 'por pessoa',
    'besides (Coin)100 for every person invited, 10% of the first-level reward share, and 5% of the second-level reward share':
        'besides (Coin)100 for every person invited, 10% of the first-level reward share, and 5% of the second-level reward share',
    '₹5 additional bonus of ₹5/person': '₹5 additional bonus of ₹5/person',
    'Register now': 'Register now',
    'Submission succeed': 'Submissão é bem sucedida',
    'The audit duration is about 5 hours, please be patient and wait for the audit to pass':
        'A duração da auditoria é de cerca de 5 horas, por favor, seja paciente e aguarde a aprovação da auditoria.',
    'If you submit the information incorrectly, you can resubmit your registration':
        'Se você enviar as informações incorretamente, você pode reenviar seu registro',
    Congratulations: 'Parabéns',
    'I know': 'I know',
    "From now on, if 100 users are invited within 7 days, in addition to the platform's existing rewards":
        'A partir de agora, se 100 usuários forem convidados dentro de 7 dias, além das recompensas existentes da plataforma',
    '100 gold coins /person plus 10% first-level reward plus 5% second-level reward':
        '100 moedas de ouro /pessoa mais 10% de recompensa de primeiro nível mais 5% de recompensa de segundo nível',
    'you will also receive': 'você também receberá',
    'additional promotional reward': 'promocional adicional',
    '₹5/person': 'R$0.5/ recompensa',
    "After reaching 100 valid invitees, you can contact the platform's staff to get the reward":
        'Depois de chegar a 100 convidados válidos, você pode entrar em contato com a equipe da plataforma para obter a recompensa',
    'Note: On the first day, invitees up to 100  can contact our staff for withdrawal immediately':
        ' Nota: No primeiro dia, os convidados até 100 podem entrar em contato com nossa equipe para retirada imediata',
    'Checkout Contact Whatsapp': 'Contato de checkout Whatsapp',
    'If you need a dedicated promotional poster,  you can contact our staff to design':
        'Se você precisar de um pôster promocional dedicado, você pode entrar em contato com nossa equipe para projetar',
    'Social media addresses': 'Endereços de mídia social',
    // 拼多多
    'My puzzles':'Quebra-cabeças',
    'My cards':'Minhas cartas',
    'Enter name':'Digite nome',
    'Enter phone':'Digite telefone',
    'Enter address':'Digite endereço',
    'Name':'Nome',
    'Phone No':'Telefone No',
    'Address':'Endereço',
    'Submit':'Enviar',
    'Rules':'Regras',
    'Money':'Dinheiro',
    'Coins':'Moedas',
    'Collect gift cards':'Colete cartões de presente',
    'Download APP':'Baixar APP',
    'Open treasure box':'Caixa de tesouro aberta',
    'click here for more':'clique aqui para mais',
    'You have':'Você tem',
    'chances to treasure box':'chances de caixa de tesouro',
    'Deadline':'Prazo',
    'Open treasure box rule':'Regra da caixa do tesouro aberta',
    'Activity Rules':'Regras de Atividade',
    'Each person will be given two chances to open the box, and each time you open the box, you will get 3 puzzles.':'Cada pessoa terá duas chances de abrir a caixa, e cada vez que abrir a caixa, você terá 3 quebra-cabeças.',
    '1 chance to open a treasure box after login every day':'1 chance de abrir uma caixa de tesouros após o login todos os dias',
    'only available on the same day':'disponível apenas no mesmo dia',
    'Every time you invite a new friend, you get a +1 chance to open your chest':'Toda vez que você convida um novo amigo, você tem uma chance +1 de abrir o peito',
    'Gather together the puzzles':'Reúna os quebra-cabeças',
    'By opening the treasure box, you can get random puzzles, gather together four complete puzzles, which can be combined with mobile phones, cash, electronic products, gold coins and other gift cards':'Ao abrir a caixa do tesouro, você pode obter quebra-cabeças aleatórios, reunir quatro quebra-cabeças completos, que podem ser combinados com telefones celulares, dinheiro, produtos eletrônicos, moedas de ouro e outros cartões de presente',
    'Gift exchange':'Troca de presentes',
    'When a complete card is generated, please click to exchange it directly. Please fill in the correct address and telephone information to prevent mailing failure':'Quando um cartão completo for gerado, clique para trocá-lo diretamente.  Preencha o endereço correto e as informações telefônicas para evitar falhas de e-mail',
    "Invite friends Let's open treasure box together":'Convide amigos Vamos abrir a caixa do tesouro juntos',
    'For every user invited to participate, you will get 1 chance to open the treasure box (cumulative)':'Para cada usuário convidado a participar, você terá 1 chance de abrir a caixa do tesouro (cumulativo)',
    'To Invite':'Para convidar',
    'Congratulations to obtain':'Parabéns para obter',
    'Congratulations on your gift card puzzles':'Parabéns por seus quebra-cabeças de cartão de presente',
    'To balance':'Para equilibrar',
    // 转盘
    'Get':'obter',
    'Get Gift':'obter presente',
    'My Prize':'meu prêmio',
    '100% WINNING':'100% taxa de vitória',
    'PLAY':'começar',
    "It's a pity that you didn't win the prize, and you are presented with ":'É uma pena que você não ganhe o prêmio, e você seja apresentado com ',
    '5 coins':'5 moedas',
    'The number of times today has been used up, please come tomorrow':'O número de vezes que hoje se esgotou, por favor, venha amanhã',
    'Confirm':'Confirmar',
    'Congratulations':'Parabéns',

    
    'You have One Cash bonus Please get it asap':'Você tem um bônus em dinheiro Por favor, pegue o mais rápido possível',
    'To complete':'Ir para completar',
    'Start':'Início',
    'Keep On! Do more task, Earn more money':'Continuem! Faça mais tarefas, ganhe mais dinheiro',
    'You got':'Você tem',
    'CompletePrimeTask':(num)=>{
        return `Tarefa completa do ${num} Prime`
    },
    'Accumulated cash':'Dinheiro acumulado',
    'Withdraw':'Sacar',
    'Event period':'Tempo de evento',
    'Withdrawl instruction':'Instrução de retirada',
    'The cash can be withdrawn immediately after the event over. If the cash is not withdrawn in time, the system will automatically transfer the accumulated cash to your platform account, which can be withdrawn at any time~':'O dinheiro pode ser retirado imediatamente após o término do evento. Se o dinheiro não for retirado a tempo, o sistema irá transferir automaticamente o dinheiro acumulado para a conta da sua plataforma, que pode ser retirado a qualquer momento ~ Quanto mais amigos você convidar, mais caixas de presente você ganha ~',
    'Invite Now':'Convide Agora',
    'Current Gift Pack':'Pacote de presente atual',
    'This cash gift pack can be opened by inviting':'Este pacote de presente em dinheiro pode ser aberto convidando',
    'people, and only':'pessoas, e apenas',
    'left you can get it':'sobrando para você pegá-lo',
    'Current Mystery Package':'Pacote Mistério Atual',
    'Congratulations! You get':'Parabéns! Você tem',
    'The accumulated cash that has been distributed to you can be withdrawn immediately after the event ends':'O dinheiro acumulado que foi distribuído a você pode ser retirado imediatamente após o término do evento.',
    'The more friends you invite':'Quanto mais amigos você convidar',
    'the more gift boxes you get~':'mais caixas de presente você ganha ~',
    'During the event period, invite users through this event page to get the opportunity to open the cash gift package.':'Durante o período do evento, convide os usuários por meio desta página do evento para ter a oportunidade de abrir o pacote de presente em dinheiro.',
    'The more friends you invite, the more gift packs you get':'Quanto mais amigos você convidar, mais pacotes de presentes você receberá.',
    'After the activity is over, you can withdraw cash. If you don`t withdraw cash in time, the system will automatically transfer the accumulated cash you get to your platform account':'Após o término da atividade, você pode sacar dinheiro. Se você não sacar dinheiro a tempo, o sistema irá transferir automaticamente o dinheiro acumulado que você receber para a sua conta da plataforma.',
    'Inviting friends can also get 100 gold coins/person on the platform, and corresponding 10% and 5% distribution rewards':'Convidar amigos também pode obter 100 moedas de ouro / pessoa na plataforma e correspondentes recompensas de distribuição de 10% e 5%',
    'This event has ended':'Este evento terminou',
    'This event has ended. If you have participated in the event, the reward has been issued to your account, please check.  Please stay tuned for the next event~':'Este evento terminou. Se você participou do evento, o prêmio foi emitido para sua conta, verifique. Fique ligado no próximo evento ~',
    'You can still get platform rewards if you invite friends':'Você ainda pode obter prêmios de plataforma se convidar amigos',
    'Rules':'As regras',
    'Invitation':'Registro de',
    'record':'convite',
    'Invitation record':'Registro de convite',
    'Invite':'Convide',
    'to join':'para aderir',
    'Activity Rules':'Regras de Atividade',
    'left you can get it':'sobrando para você pegá-lo',
    "people have successfully withdrawn": "pessoas foram retiradas com sucesso",
	"Deadline": "Prazo final",
	"Congratulations! please apply for withdrawal asap": "Parabéns! por favor solicite a retirada o mais rápido possível",
	"more to complete": "mais para completar",
	"withdraw to": "retirar para",
	"Wheel of fortune": "Roda da fortuna",
	"Invite Friends": "Convide amigos",
	"You can invite friends to win the lottery": "Você pode convidar amigos para ganhar na loteria",
	"1 more time for each friend invited": "Mais 1 vez para cada amigo convidado",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "o dinheiro sacado será acumulado na conta de atividade do usuário, o diamante sacado será convertido em dinheiro acumulado na conta de atividade, sacado para saque direto pode sacar imediatamente",
	"to your": "para o seu",
	"Cash prizes drawn up to": "Prêmios em dinheiro sorteados até",
	"during the activity can be withdrawn immediately": "durante a atividade pode ser retirado imediatamente",
	"10% handling charge": "10% de taxa de manuseio",
	"will be charged for withdrawal": "será cobrado pela retirada",
	"Each friend invited will be rewarded with": "Cada amigo convidado será recompensado com",
	"100 coins +10% coin commission": "100 moedas + 10% de comissão de moedas",
	"which will be distributed in the Yowin": "que será distribuído no Yowin",
	"invite account": "convidar conta",
	"and can be withdrawn separately": "e pode ser retirado separadamente",
	"Congratulations": "Parabéns",
	"Win million Cash with all players Withdrawal arrives in seconds": "Ganhe milhões de dinheiro com todos os jogadores A retirada chega em segundos",
	"Flop": "Falhar",
	"Your friend invite you to join": "Seu amigo convida você para participar",
	"For each friend invited,you will have an additional chance to draw": "Para cada amigo convidado, você terá uma chance adicional de sortear",
	"To Invite": "Convidar",
	"Luck over 99% of users": "Sorte de mais de 99% dos usuários",
    "Luck over":'Sorte de mais de',
	"of users":'dos usuários',
	"DOWNLOAD APP": "BAIXAR APLICATIVO",
	"Get more cash&withdraw": "Obtenha mais dinheiro e saque",
	"win more ruppes&withdraw": "ganhe mais ruppes e retire",
	"successfully withdrew": "retirou-se com sucesso",
	"Easy Money": "Dinheiro fácil",
	"Others": "Outras"
}