export const shopPt = {
    'Coins':'Moedas',
    'Balance':'Saldo',
    'Withdraw':'Sacar',
    'Cash & Prize':'Dinheiro e prêmio',
    'Free Get':'Ganhe grátis',
    'Phone Numer':'Número de telefone',
    'Submit':'Enviar',
    'Insufficient coins':'Moedas insuficientes',
    'First Name':'Primeiro nome',
    'Last Name':'Último nome',
    'Address':'Endereço',
    'Please fill in the mailing address':'Por favor, preencha o endereço de correspondência',
    'Please enter the information completely':'Please enter the information completely',
    'Withdraw to':'Retirar para',
    'Submitted successfully':'Submetido com sucesso',
    'We will ship to you after review, please wait patiently':'Nós enviaremos para você após revisão, por favor, aguarde pacientemente',
    'Earn More Money':'Ganhe mais dinheiro',
    'Lucky Spin':'Rodada de sorte',
    'My rewards':'Minhas recompensas',
    'Recharge card':'cartão de recarga',
    'Toy':'Brinquedo',
    'fragments':'fragmentos',
    'Fragments':'Fragmentos',
    'Gift card':'cartão-presente',
    'View':'Veja',
    'Loading': 'Carregando',
}