export const activityFr = {
    "people have successfully withdrawn": "personnes se sont retirées avec succès",
	"Deadline": "Date limite",
	"Congratulations! please apply for withdrawal asap": "Toutes nos félicitations! veuillez demander le retrait dès que possible",
	"more to complete": "plus à compléter",
	"withdraw to": "retirer à",
	"Wheel of fortune": "Roue de la Fortune",
	"Invite Friends": "Inviter des amis",
	"You can invite friends to win the lottery": "Vous pouvez inviter des amis à gagner à la loterie",
	"1 more time for each friend invited": "1 fois de plus pour chaque ami invité",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "l'argent tiré sera accumulé sur le compte d'activité de l'utilisateur, le diamant tiré sera converti en argent accumulé sur le compte d'activité, tiré au retrait direct peut être retiré immédiatement",
	"to your": "à ton",
	"Cash prizes drawn up to": "Des prix en espèces tirés à",
	"during the activity can be withdrawn immediately": "pendant l'activité peut être retiré immédiatement",
	"10% handling charge": "10% de frais de manutention",
	"will be charged for withdrawal": "sera facturé pour le retrait",
	"Each friend invited will be rewarded with": "Chaque ami invité sera récompensé par",
	"100 coins +10% coin commission": "100 pièces + 10 % de commission sur les pièces",
	"which will be distributed in the Yowin": "qui sera distribué dans le Yowin",
	"invite account": "inviter un compte",
	"and can be withdrawn separately": "et peut être retiré séparément",
	"Congratulations": "Toutes nos félicitations",
	"Win million Cash with all players Withdrawal arrives in seconds": "Gagnez des millions d'argent avec tous les joueurs Le retrait arrive en quelques secondes",
	"Flop": "Fiasco",
	"Your friend invite you to join": "Votre ami vous invite à rejoindre",
	"For each friend invited,you will have an additional chance to draw": "Pour chaque ami invité, vous aurez une chance supplémentaire de tirer",
	"To Invite": "Inviter",
	"Luck over 99% of users": "Chance plus de 99% des utilisateurs",
	"Luck over":'Chance plus de',
	"of users":'des utilisateurs',
	"DOWNLOAD APP": "TÉLÉCHARGER L'APPLICATION",
	"Get more cash&withdraw": "Obtenez plus d'argent et retirez",
	"win more ruppes&withdraw": "gagner plus de ruppes et retirer",
	"successfully withdrew": "retiré avec succès",
	"Easy Money": "L'argent facile",
	"Others": "Autres"
}