export const activityRu = {
	title: 'Набор амбасадараў',
    subTitle: 'Штодзённая разліковая камісія',
    invitation: 'За кожнае запрашэнне,',
    AWARD: 'Мы ўзнагародзім дадаткова',
	"₹5": "5 ₹",
	"NO CAP": "БЕЗ КАПЫ",
	describe:'Калі вы ўплывовы чалавек і маеце ўласную платформу для прасоўвання, такую ​​як Youtube, Telegram, FB, Instagram і г.д., або ў вас ёсць мноства фан-рэсурсаў',
	"Please contact us, we can give you": "Калі ласка, звяжыцеся з намі, мы можам даць вам",
	"name": "імя",
	"Phone NO": "Тэлефон НЕ",
	"What social media do you use(Facebook/Ins/telegram/etc.)": "Якімі сацыяльнымі сеткамі вы карыстаецеся (Facebook/Ins/telegram/і г.д.)",
	"Numbers of followers": "Колькасць падпісчыкаў",
	"Contant US(wa)": "Пастаянна ЗША (ва)",
	"Copy": "Копія",
	"submit": "прадставіць",
	"As the beginning of the event, we only recruit": "У пачатку мерапрыемства мы толькі набіраем",
	"Ambassadors": "Паслы",
	"besides": "акрамя таго",
	"for every person invited": "для кожнага запрошанага чалавека",
	"of the second-level reward share": "долі ўзнагароджання другога ўзроўню",
	"and": "і",
	"additional bonus of": "дадатковы бонус ",
	"person": "асоба",
	"besides (Coin)100 for every person invited, 10% of the first-level reward share, and 5% of the second-level reward share": "акрамя (Манета)100 за кожнага запрошанага чалавека, 10% долі ўзнагароды першага ўзроўню і 5% долі ўзнагароды другога ўзроўню",
	"₹5 additional bonus of ₹5/person": "Дадатковы бонус 5 рупій на чалавека",
	"Register now": "Зарэгіструйцеся зараз",
	"Submission succeed": "Адпраўка прайшла паспяхова",
	"The audit duration is about 5 hours, please be patient and wait for the audit to pass": "Працягласць аўдыту складае каля 5 гадзін, калі ласка, набярыцеся цярпення і пачакайце, пакуль праверка пройдзе",
	"If you submit the information incorrectly, you can resubmit your registration": "Калі вы падалі інфармацыю няправільна, вы можаце паўторна адправіць рэгістрацыю",
	"Congratulations": "Віншую!",
	"I know": "Я ведаю",
	"From now on, if 100 users are invited within 7 days, in addition to the platforms existing rewards": "«З гэтага моманту, калі 100 карыстальнікаў будуць запрошаны на працягу 7 дзён, у дадатак да існуючых узнагарод платформы»",
	"100 gold coins /person plus 10% first-level reward plus 5% second-level reward": "100 залатых манет на чалавека плюс 10% узнагароды першага ўзроўню плюс 5% узнагароды другога ўзроўню",
	"you will also receive": "вы таксама атрымаеце",
	"additional promotional reward": "дадатковая рэкламная ўзнагарода",
	"₹5/person": "5 рупій/чалавек",
	"After reaching 100 valid invitees, you can contact the platforms staff to get the reward": "Пасля дасягнення 100 сапраўдных запрошаных вы можаце звязацца з персаналам платформы, каб атрымаць узнагароду",
	"Note": "Нататка",
	"Checkout Contact Whatsapp": "Звязацца з Whatsapp",
	"If you need a dedicated promotional poster, you can contact our staff to design": "Калі вам патрэбен спецыяльны рэкламны плакат, вы можаце звязацца з нашымі супрацоўнікамі, каб распрацаваць",
	"Social media addresses": "Адрасы ў сацыяльных сетках",
	"Accumulated cash": "Назапашаныя грашовыя сродкі",
	"Withdraw": "Зняць",
	"Event period": "Перыяд падзей",
	"Withdrawl instruction": "Інструкцыя па зняцці",
	"The cash can be withdrawn immediately after the event over. If the cash is not withdrawn in time, the system will automatically transfer the accumulated cash to your platform account, which can be withdrawn at any time~": "Наяўныя можна зняць адразу пасля заканчэння мерапрыемства. Калі наяўныя грошы не будуць знятыя своечасова, сістэма аўтаматычна перавядзе назапашаныя грошы на ваш рахунак платформы, які можна зняць у любы час~",
	"Invite Now": "Запрасіць зараз",
	"Current Gift Pack": "Бягучы падарункавы пакет",
	"This cash gift pack can be opened by inviting": "Гэты грашовы падарункавы пакет можна адкрыць, запрасіўшы",
	"people, and only": "людзі, і толькі ",
	"left you can get it": "засталося, вы можаце атрымаць гэта",
	"Current Mystery Package": "Бягучы пакет Mystery",
	"Congratulations! You get": "Віншую! Вы атрымліваеце",
	"The accumulated cash that has been distributed to you can be withdrawn immediately after the event ends": "Назапашаныя грашовыя сродкі, якія былі размеркаваны вам, можна зняць адразу пасля заканчэння мерапрыемства.",
	"The more friends you invite": "Чым больш сяброў вы запросіце",
	"the more gift boxes you get~": "тым больш падарункавых скрынак вы атрымаеце ~",
	"During the event period, invite users through this event page to get the opportunity to open the cash gift package.": "У перыяд мерапрыемства запрашайце карыстальнікаў праз гэтую старонку падзеі, каб атрымаць магчымасць адкрыць падарункавы пакет наяўнымі».",
	"The more friends you invite, the more gift packs you get": "Чым больш сяброў вы запросіце, тым больш падарункавых пакетаў вы атрымаеце",
	"After the activity is over, you can withdraw cash. If you don`t withdraw cash in time, the system will automatically transfer the accumulated cash you get to your platform account": "Пасля заканчэння дзейнасці вы можаце здымаць наяўныя. Калі вы не знялі наяўныя грошы своечасова, сістэма аўтаматычна перавядзе назапашаныя грошы на ваш рахунак платформы.",
	"Inviting friends can also get 100 gold coins/person on the platform, and corresponding 10% and 5% distribution rewards": "Запрашаючы сяброў, таксама можна атрымаць 100 залатых манет на чалавека на платформе і адпаведныя ўзнагароды ў памеры 10% і 5%",
	"This event has ended": "Гэта падзея скончылася",
	"This event has ended. If you have participated in the event, the reward has been issued to your account, please check.  Please stay tuned for the next event~": "Гэта мерапрыемства скончылася. Калі вы ўдзельнічалі ў мерапрыемстве, узнагарода была выдадзена на ваш рахунак, праверце. Калі ласка, сачыце за навінамі для наступнай падзеі ~",
	"You can still get platform rewards if you invite friends": "Вы ўсё яшчэ можаце атрымаць узнагароды платформы, калі запрасіце сяброў",
	"Rules": "Правілы",
	"Invitation": "Запрашэнне",
	"record": "запіс",
	"Invitation record": "Запрашэнне",
	"Invite": "запрасіць",
	"to join": "далучыцца",
	"Activity Rules": "Правілы дзейнасці",
	"You have One Cash bonus Please get it asap": "У вас ёсць адзін грашовы бонус, калі ласка, атрымайце яго як мага хутчэй",
	"To complete": "Каб завяршыць",
	"Start": "Пачаць",
	"Keep On! Do more task, Earn more money": "Працягваць! Рабіце больш задач, зарабляйце больш грошай",
	"You got": "Вы атрымалі",
	"Note: On the first day, invitees up to 100  can contact our staff for withdrawal immediately": "Заўвага: у першы дзень запрошаныя да 100 могуць неадкладна звязацца з нашымі супрацоўнікамі для адклікання",
	"Get Gift": "Атрымаць падарунак",
	"My Prize": "Мой прыз",
	"100% WINNING": "100% ПЕРАМОГА",
	"PLAY": "ІГРАЦЬ",
	"It's a pity that you didn't win the prize, and you are presented with": "Шкада, што ты не выйграў прыз, а табе ўручаюць",
	"5 coins": "5 манет",
	"The number of times today has been used up, please come tomorrow": "Колькасць разоў сёння было выкарыстана, калі ласка, прыходзьце заўтра",
	"Congratulations": "Віншую!",
	"To balance": "Каб збалансаваць",
	"Congratulations on your gift card puzzles": "Віншуем з галаваломкамі з падарункавай картай",
	"Congratulations to obtain": "Віншуем з атрыманнем",
	"To Invite": "Каб запрасіць",
	"For every user invited to participate, you will get 1 chance to open the treasure box (cumulative)": "Для кожнага карыстальніка, запрошанага да ўдзелу, вы атрымаеце 1 шанец адкрыць скрыню са скарбамі (сукупна)",
	"Invite friends Let's open treasure box together": "Запрасіце сяброў Давайце разам адкрыем скрыню са скарбамі",
	"When a complete card is generated, please click to exchange it directly. Please fill in the correct address and telephone information to prevent mailing failure": "Калі поўная карта будзе створана, націсніце, каб абмяняць яе непасрэдна. Калі ласка, увядзіце правільны адрас і інфармацыю па тэлефоне, каб прадухіліць збой па пошце",
	"Gift exchange": "Абмен падарункамі",
	"By opening the treasure box, you can get random puzzles, gather together four complete puzzles, which can be combined with mobile phones, cash, electronic products, gold coins and other gift cards": "Адкрыўшы скрыню са скарбамі, вы можаце атрымаць выпадковыя галаваломкі, сабраць чатыры поўныя галаваломкі, якія можна аб'яднаць з мабільнымі тэлефонамі, наяўнымі, электроннымі прадуктамі, залатымі манетамі і іншымі падарункавымі картамі",
	"Gather together the puzzles": "Збярыце пазлы",
	"Every time you invite a new friend, you get a +1 chance to open your chest": "Кожны раз, калі вы запрашаеце новага сябра, вы атрымліваеце +1 шанец адкрыць свой куфар",
	"only available on the same day": "даступна толькі ў той жа дзень",
	"1 chance to open a treasure box after login every day": "1 шанец адкрыць скрыню са скарбамі кожны дзень пасля ўваходу ў сістэму",
	"Each person will be given two chances to open the box, and each time you open the box, you will get 3 puzzles.": "Кожнаму чалавеку будзе дадзена два шанцы адкрыць скрыню, і кожны раз, калі вы адкрыеце скрынку, вы атрымаеце 3 галаваломкі.",
	"Open treasure box rule": "Правіла адкрытай скрыні з скарбамі",
	"Deadline": "Крайні тэрмін",
	"chances to treasure box": "шанцы атрымаць скрыню са скарбамі",
	"You have": "У цябе ёсць",
	"click here for more": "націсніце тут для атрымання дадатковай інфармацыі",
	"Open treasure box": "Адкрыйце скрыню са скарбамі",
	"Download APP": "Спампаваць APP",
	"Collect gift cards": "Збірайце падарункавыя карты",
	"Money": "Грошы",
	"Address": "Адрас",
	"Name": "Імя",
	"Enter address": "Увядзіце адрас",
	"Enter phone": "Увядзіце тэлефон",
	"Enter name": "Увядзіце імя",
	"My cards": "Мае карты",
	"My puzzles": "Мае галаваломкі",
	"people have successfully withdrawn": "человек успешно вышли",
	"Deadline": "Срок",
	"Congratulations! please apply for withdrawal asap": "Поздравляем! пожалуйста, подайте заявку на вывод как можно скорее",
	"more to complete": "больше, чтобы закончить",
	"withdraw to": "уйти в",
	"Wheel of fortune": "Колесо фортуны",
	"Invite Friends": "Пригласить друзей",
	"You can invite friends to win the lottery": "Вы можете пригласить друзей, чтобы выиграть в лотерею",
	"1 more time for each friend invited": "Еще 1 раз за каждого приглашенного друга",
	"the cash drawn will be accumulated to the user activity account, the diamond drawn will be converted into cash accumulated to the activity account, drawn to direct withdrawal can immediately withdraw": "наличные деньги будут накапливаться на счете активности пользователя, нарисованный бриллиант будет преобразован в наличные деньги, накопленные на счете активности, нарисованные для прямого вывода могут быть немедленно сняты",
	"to your": "на ваш",
	"Cash prizes drawn up to": "Денежные призы разыгрываются до",
	"during the activity can be withdrawn immediately": "во время активности может быть отозван немедленно",
	"10% handling charge": "10% сбор за обработку",
	"will be charged for withdrawal": "будет взиматься плата за вывод",
	"Each friend invited will be rewarded with": "Каждый приглашенный друг будет вознагражден",
	"100 coins +10% coin commission": "100 монет +10% комиссия за монеты",
	"which will be distributed in the Yowin": "который будет распространяться в Yowin",
	"invite account": "пригласить аккаунт",
	"and can be withdrawn separately": "и можно снять отдельно",
	"Congratulations": "Поздравления",
	"Win million Cash with all players Withdrawal arrives in seconds": "Выиграйте миллион наличными со всеми игроками Вывод средств происходит за считанные секунды",
	"Flop": "Флоп",
	"Your friend invite you to join": "Ваш друг приглашает вас присоединиться",
	"For each friend invited,you will have an additional chance to draw": "За каждого приглашенного друга у вас будет дополнительный шанс розыгрыша",
	"To Invite": "Пригласить",
	"Luck over 99% of users": "Удача более 99% пользователей",
	"Luck over":'Удача более',
	"of users":'пользователей',
	"DOWNLOAD APP": "СКАЧАТЬ ПРИЛОЖЕНИЕ",
	"Get more cash&withdraw": "Получить больше наличных и снять",
	"win more ruppes&withdraw": "выиграть больше рупий и снять деньги",
	"successfully withdrew": "успешно отозвал",
	"Easy Money": "Шальные деньги",
	"Others": "Другие",
	'Get':'Получить'
}