export const shopRu = {
	"Balance": "Баланс",
	"Cash & Prize": "Грашовыя сродкі і прыз",
	"Free Get": "Бясплатна атрымаць",
	"Phone Numer": "Нумар тэлефона",
	"First Name": "Імя",
	"Last Name": "Прозвішча",
	"Address": "Адрас",
	"Please fill in the mailing address": "Калі ласка, увядзіце паштовы адрас",
	"Please enter the information completely": "Калі ласка, увядзіце інфармацыю цалкам",
	"Submitted successfully": "Паспяхова адпраўлена",
	"We will ship to you after review, please wait patiently": "Мы адправім вам пасля агляду, калі ласка, цярпліва пачакайце",
	"Earn More Money": "Зарабляйце больш грошай",
	"Lucky Spin": "Lucky Spin",
	"My rewards": "Мае ўзнагароды",
	"Recharge card": "Карта папаўнення",
	"Toy": "цацка",
	"fragments": "фрагменты",
	"Gift card": "Падарункавая карта",
	"View": "Глядзець",
}